version: 2.1
orbs:
  ruby: circleci/ruby@1.0.4
jobs:
  test_3_1:
    docker:
      - image: cimg/ruby:3.1.7
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake
  test_3_2:
    docker:
      - image: cimg/ruby:3.2.6
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake
  test_3_3:
    docker:
      - image: cimg/ruby:3.3.8
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rake
workflows:
  version: 2
  deploy:
    jobs:
      - test_3_1
      - test_3_2
      - test_3_3
